baseURL = "/"
languageCode = "en-us"
title = "Goatchella | 2022"
theme = "twenty-twenty"
relativeURLs = true

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Travel"
URL = "travel/"
weight = 2

[[menu.main]]
name = "About"
URL = "about/"
weight = 3

[params]
# Meta data
description = "Who makes this stuff?"
author = "Silly Criblanians"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# banner
[params.banner]
#heading = "Goatchella 2022"
image = "images/banner.jpg"

# blog
[params.blog]
heading = "Music, Art, Albania\n\nand GOATS!"

# call to action
[params.call_to_action]
enable = true
title = "Bitinckë or Bust!"
content = "Join us in lovely Bitinckë, Albania for a week-long event. Book your travel plans now!"
button_label = "Travel"
button_url = "travel/"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item]]
image = "images/the-bleatles.png"

[[params.gallery.gallery_item]]
image = "images/vandoren.png"

[[params.gallery.gallery_item]]
image = "images/goatsmack.png"

[[params.gallery.gallery_item]]
image = "images/okgoat.png"

[[params.gallery.gallery_item]]
image = "images/ladybaabaa.png"

[[params.gallery.gallery_item]]
image = "images/bluehorngroup.png"

[params.footer]
title = "About Us"
content = "Don't mind us. We're just a bunch of goat-obsessed criblanians."
address = "42 Unnamed, Road, Bitinckë, Albania"
hours = "Weekdays, 9:00AM–4:20PM, GMT+1"
copyright = "Copyright &copy; 2022 Silly Nonsense, Inc."

[params.social]
yelp = "#"
facebook = "#"
twitter = "#"
instagram = "#"
email = "#"
linkedin = "#"


