name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker run --rm -v $(pwd)/site:/src klakegg/hugo:0.92.1

      - name: Package & Publish
        uses: docker/build-push-action@v2
        with:
          image: pdugas/goatchella
          tags: latest
          registry: ghcr.io
          platforms: linux/amd64,linux/arm64
          push: true
