name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish
        run: |
          docker pull ghcr.io/pdugas/goatchella:latest || true
          docker build \
            --cache-from ghcr.io/pdugas/goatchella:latest \
            -t ghcr.io/pdugas/goatchella:latest \
            .
          docker push ghcr.io/pdugas/goatchella:latest

